# 운영에서 사용하는 docker-compose.yml
# 호스트머신 5432 : 컨테이너 내부 5432 매핑

version: "3"

services:
  study-db:
    image: postgres
    ports:
      - 5432:5432
      environment:
        POSTGRES_PASSWORD: "1568919am!"
        POSTGRES_USER: "seungmoo"
        POSTGRES_DB: "springdata_test"

